# Generated by Django 2.1.2 on 2019-05-16 05:13

import Venter.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0028_file_file_saved_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default-avatar.png', upload_to=Venter.helpers.get_user_profile_picture_path),
        ),
    ]
