# Generated by Django 2.1.2 on 2019-06-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0037_auto_20190625_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposal_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
