# Generated by Django 2.1.2 on 2019-06-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0039_auto_20190625_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='proposal_name',
            new_name='domain_name',
        ),
    ]
