# Generated by Django 2.1.2 on 2019-07-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0041_file_domain_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='domain_present',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
