# Generated by Django 2.1.2 on 2019-07-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0042_auto_20190708_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
