# Generated by Django 2.1.2 on 2019-07-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0046_auto_20190719_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='model_choice',
            field=models.CharField(blank=True, choices=[('sentence_model', 'sentence_model'), ('keyword_model', 'keyword_model')], max_length=15, null=True),
        ),
    ]
