# Generated by Django 2.1.2 on 2019-07-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0047_file_model_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='wordcloud_data',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
    ]
